### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by robinaar** [WinSSHTerm/WSL_Starter#1]
Does not work on my machine. 

Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0xffffffff Error: 0xffffffff (null) > Finished

> C:\Users\robin\OneDrive\Bureaublad\kali.exe run "echo '***' | sudo -S dpkg -l | grep ^ii | sed 's_  _\t_g' | cut -f 2 | grep openssh-server 1> /dev/null && echo '***' | sudo -S cp /etc/ssh/sshd_config /etc/ssh/sshd_config.winsshterm.bak && echo '***' | sudo -S apt-get purge -y openssh-server 2>/dev/null"
Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0xffffffff Error: 0xffffffff (null) > Finished

> C:\Users\robin\OneDrive\Bureaublad\kali.exe run "echo '***' | sudo -S apt-get -y update && echo '***' | sudo -S DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server"
Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0xffffffff Error: 0xffffffff (null) > Finished

> C:\Users\robin\OneDrive\Bureaublad\kali.exe run "echo '***' | sudo -S ssh-keygen -A"
Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0xffffffff Error: 0xffffffff (null) > Finished

> C:\Users\robin\OneDrive\Bureaublad\kali.exe run "echo '***' | sudo -S sed -i -e '/^#[[:space:]]*[[:space:]]*Port[[:space:]].*/ s/^#[[:space:]]*[[:space:]]*\(Port\)[[:space:]]\(.*\)/\1 2222/i' -- /etc/ssh/sshd_config"
Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0xffffffff Error: 0xffffffff (null) > Finished

> C:\Users\robin\OneDrive\Bureaublad\kali.exe run "echo '***' | sudo -S sed -i -e '/^#[[:space:]]*[[:space:]]*ListenAddress[[:space:]].*0\.0\.0\.0/ s/^#[[:space:]]*[[:space:]]*\(ListenAddress\)[[:space:]]\(.*\)/\1 127.0.0.1/i' -- /etc/ssh/sshd_config"
Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0xffffffff Error: 0xffffffff (null) > Finished

> C:\Users\robin\OneDrive\Bureaublad\kali.exe run "echo '***' | sudo -S sed -i -e '/^[[:space:]]*PasswordAuthentication[[:space:]].*/ s/^[[:space:]]*\(PasswordAuthentication\)[[:space:]]\(.*\)/\1 yes/i' -- /etc/ssh/sshd_config"
Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0xffffffff Error: 0xffffffff (null) > Finished

> C:\Users\robin\OneDrive\Bureaublad\kali.exe run "echo '***' | sudo -S diff /etc/ssh/sshd_config /etc/ssh/sshd_config.winsshterm.bak &> /dev/null; if [ $? -ne 0 ]; then echo '***' | sudo -S mv /etc/ssh/sshd_config.winsshterm.bak /etc/ssh/sshd_config.$(date +%Y%m%d_%H%M%S).bak; else echo '***' | sudo -S rm /etc/ssh/sshd_config.winsshterm.bak; fi
Installing, this may take a few minutes... WslRegisterDistribution failed with error: 0xffffffff Error: 0xffffffff (null) > Finished

**Comment by WinSSHTerm** [comment]
It looks like the distribution was not correctly installed. Probably there is some other process listening on Port 53 (see https://github.com/microsoft/WSL/issues/4364)
