### ISSUE TITLE
Debian.xml does not validate

### ISSUE THREAD

**Issue by mooh-pooh** [WinSSHTerm/WSL_Starter#2]
![image](https://github.com/WinSSHTerm/WSL_Starter/assets/8424782/92fdb0c9-5415-4f8a-8b89-7354dbf0ed2c)

**Comment by WinSSHTerm** [comment]
Thanks for your feedback. The XML syntax has changed with WinSSHTerm 2.33.0. Looks like you are still using an older version. Updating to the current version should solve the issue
